// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/checkin-redesign/HeroCard.tsx": () => import("../components/mockups/checkin-redesign/HeroCard.tsx"),
  "./components/mockups/checkin-redesign/SplitScreen.tsx": () => import("../components/mockups/checkin-redesign/SplitScreen.tsx")
};
